[package]
name = "copo"
version = "0.1.0"
authors = ["MetallicSquid <guillame.Macneil@ccoex.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.15"
failure = "0.1.8"
exitfailure = "0.5.1"
indicatif = "0.15.0"
console = "0.11.3"
ctrlc = "3.1.4"
